'use strict';

var Match = require('./match.js');

var match = new Match("Player 1", "Player 2");
match.p1.gamesWon = 0;
match.p2.gamesWon = 0;
console.log("--Initial Condition--");
match.score();
console.log("Start");
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 1");');
match.pointWonBy("Player 1");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();
console.log('match.pointWonBy("Player 2");');
match.pointWonBy("Player 2");
match.score();